class Character < ApplicationRecord
  belongs_to :user
  belongs_to :character_class, polymorphic: true, dependent: :destroy

  before_create :set_default_history

  private

  def set_default_history
    return if self.history.present?

    histories_by_class = {
      'Barbarian' => [
        "#{name} was once a member of a powerful tribe of warriors. They were trained in all forms of combat, from hand-to-hand to martial weapons. But one day, their tribe was betrayed by one of their own, and #{name} was one of the only survivors. Consumed by rage and grief, they embarked on a relentless quest for vengeance. They embraced their inner fury, unleashing their wrath upon those who crossed their path. Their primal rage manifested in devastating displays of strength, as they became an unstoppable force, cutting a swath through their enemies with a whirlwind of fury. But as they journeyed deeper into darkness, they encountered a wise hermit who taught them the path of balance. They learned to channel their anger into purpose, becoming a defender of the innocent, a guardian of justice, and a beacon of hope in a world plagued by violence. Now, they seek revenge against their former tribe member and anyone who stands in their way.", "In a rugged tribal society, #{name} was born into a lineage of fierce warriors, their bloodline intertwined with the spirits of nature. From a young age, they were trained in the art of combat, honing their physical strength and tapping into the primal fury that dwelled within them. However, their true destiny lay beyond the confines of the tribe. Drawn to the untamed wilderness, they forged a bond with the creatures that roamed the land, becoming a protector of the wild and a fierce champion of nature. They rejected the trappings of civilization, embracing their inner beast and unleashing a storm of fury upon those who threatened the natural order. With each swing of their mighty weapon, they became an embodiment of the untamed wilderness, a force of nature that could not be tamed.", "Born into a nomadic tribe that revered ancient spirits, #{name} was marked from birth as the chosen vessel for a powerful primal entity. As they grew, they underwent rigorous spiritual training, communing with the spirits of their ancestors and absorbing their wisdom. The spirits bestowed upon them the ability to channel the elements, transforming their body into an avatar of nature's wrath. They became a living tempest, wielding storms, earthquakes, and flames with unrivaled ferocity. However, their power came at a price. The primal entity within them constantly tugged at their sanity, threatening to overwhelm their sense of self. To maintain control, they embarked on a spiritual pilgrimage, seeking to balance their mortal existence with the divine power that coursed through their veins, forever straddling the line between civilization and the untamed forces of nature."
        ],
      'Bard' => [
        "Born into a family of traveling performers, #{name} grew up amidst the whimsical melodies and lively dance steps of the circus. From a young age, they discovered a natural aptitude for music and storytelling, captivating audiences with their charismatic presence. Their wanderlust led them beyond the confines of the troupe, embarking on a journey as a solo performer. With their versatile talents, they used music, poetry, and dramatic flair to uplift spirits, inspire bravery, and sow the seeds of rebellion against oppressive regimes. Each stage they set foot upon became a platform for spreading their revolutionary ideals, and with each chord struck and every word sung, they ignited a spark of hope in the hearts of those who yearned for change.", "#{name} was once a member of a prestigious academy of magic. They had always been fascinated by music and the power it held, but their teachers never understood their passion. One day, while practicing their lute in secret, the bard discovered that their music had the ability to manipulate the emotions of others. Harnessing this power, they left the academy and began to wander the land, using their music to charm and persuade those they met. However, they soon realized that their power had a dark side, and they struggled to find a balance between using it for good and succumbing to its temptation.", "Raised in a peaceful village, #{name}'s life was forever changed when a devastating raid by marauding invaders left their home in ruins. Consumed by anger and grief, they channeled their emotions into their art, honing their musical talents into a force to be reckoned with. Their songs became battle cries, empowering allies with resounding melodies and demoralizing enemies with haunting laments. Driven by their desire for vengeance, they set out on a quest to vanquish the raiders and bring justice to their fallen village. Yet, as they journeyed, they discovered that their music held the power not only to inspire conflict but also to mend wounds and bridge divides. They transformed their rage into compassion, using their performances to heal the scars left by war and unite disparate communities in a symphony of harmony."
      ],
      'Cleric' => [
        "Born into a lineage of healers, #{name} possessed an innate talent for mending both body and spirit. They were trained in the arts of herbalism and ancient remedies, becoming a skilled practitioner of alternative medicine. Their desire to alleviate suffering extended beyond the realm of physical ailments. With a natural charisma and a gift for comforting words, they offered solace to those in emotional turmoil, mending broken hearts with their empathetic presence. Their compassion and healing touch earned them a reputation as a spiritual guide and confidante. They embarked on a pilgrimage, carrying the healing light of their deity to the darkest corners of the world, bringing hope and renewal to the weary souls they encountered.", "Raised in a secluded temple, #{name} was chosen by the gods at a young age to serve as their vessel in the mortal realm. Gifted with divine powers, they devoted their life to the study of ancient scriptures, sacred rituals, and the tenets of their chosen deity. Their faith was unyielding, and their connection with the divine allowed them to wield miraculous healing magic and call upon divine wrath to smite their enemies. But their journey was not confined to the walls of their temple. They ventured into the world as a beacon of hope, extending a helping hand to those in need and spreading the teachings of their faith. Their divine mission led them on a path of compassion, forgiveness, and unwavering devotion to their gods. They left their home and joined a group of like-minded individuals, using their divine powers to fight against corruption and oppression. Though the road is long and difficult, the cleric is determined to make a difference.", "Once a hardened warrior, #{name}'s life changed forever when they experienced a divine revelation on the battlefield. Struck by a blinding light and overwhelmed by a sense of purpose, they renounced their violent ways and devoted themselves to the service of a benevolent deity. They became a spiritual warrior, wielding their newfound faith as a shield and a weapon. Their divine connection granted them the ability to bolster the strength and courage of their allies, turning the tide of battles with their inspiring presence. They became a living embodiment of their deity's virtues, a testament to the transformative power of faith. With each step they took, they sought to restore hope and bring justice to a world plagued by darkness."
      ],
      'Druid' => [
        "In the hidden groves of a sacred fae realm, #{name} was found nestled among the ancient trees, their birthright intertwined with the mystical energies of the land. Raised by ethereal guardians, they learned to harness the raw power of nature, communicating with the spirits and creatures that roamed the verdant realm. As they grew, their druidic abilities bloomed, allowing them to shape-shift into mythical beasts and call upon the forces of the elements. With the weight of their duty to protect the balance of the fae realm and the wider world, they embarked on a journey beyond their enchanted home, driven to preserve the fragile harmony of the natural world against the encroaching darkness.", "Deep within the scorched deserts, a nomadic tribe discovered #{name} amidst the relentless sandstorms, their cries echoing with a touch of ancient magic. Raised under the watchful eyes of wise shamans, they learned to tap into the primal forces of the desert, drawing strength from the scorching sun and the shifting sands. Through their druidic teachings, they found solace in the unforgiving terrain and a kinship with the desert creatures that managed to thrive. As they honed their abilities to manipulate the elements and heal both flesh and earth, they became a guardian of the desert, sworn to defend its fragile ecosystems and the nomadic tribes that called it home.", "In the misty, forgotten swamps, #{name} was discovered by a reclusive druid, hidden away from the prying eyes of civilization. Raised in solitude, they developed a profound connection with the bog's murky depths and the mystical creatures that lurked within. As they matured, their druidic powers manifested in eerie ways, allowing them to control the swirling mists, commune with shadowy beings, and summon the forces of decay and rebirth. Driven by their love for the forgotten and misunderstood, they ventured out into the world as an emissary of the swamps, spreading wisdom and defending the delicate balance between life and death that permeated their boggy home."
      ],
      'Rogue' => [
        "Born into a notorious thieves' guild, #{name} was left on the doorstep of the guild's den, destined to become a pawn in their criminal machinations. As they grew, they honed their skills in deception, stealth, and acrobatics under the watchful eye of the guild's mastermind. However, their ambition and cunning far surpassed the limits of the guild's boundaries. Unbeknownst to their criminal mentors, they secretly worked as an informant for the city guard, using their skills to undermine the guild's operations and bring justice to the streets. They navigated a treacherous world of shadows and double-crosses, always one step ahead of both their criminal associates and the law, driven by their unwavering commitment to tip the scales of justice in their favor.", "Raised on the unforgiving streets of a sprawling metropolis, #{name} learned to survive by any means necessary. From a young age, they became a skilled pickpocket, effortlessly blending into the crowds and disappearing into the labyrinthine alleyways. But beneath their thieving exterior lay a heart of gold. They used their nimble fingers and silver tongue to steal from the corrupt and redistribute wealth to the downtrodden. With each stolen purse, they became a champion of the oppressed, a masked hero for those trapped in poverty, striving to create a more egalitarian society, even if it meant working in the shadows.", "A former noble, #{name} was forced into a life of thievery when their family's fortune crumbled, leaving them destitute. Driven by a burning desire for revenge against those who wronged their family, they infiltrated high society masquerades and whispered secrets in the dimly lit corners of extravagant ballrooms. Their proficiency in disguise and subterfuge allowed them to extract invaluable information and gain the upper hand in a clandestine game of manipulation. Their ultimate goal was to dismantle the corrupt aristocracy that had destroyed their life, even if it meant using their skills to weave a web of chaos and expose the dark underbelly of their former peers."
      ],
      'Wizard' => [
        "Born into a lineage of esteemed arcanists, #{name} was destined to uphold the family's legacy of magical prowess. From an early age, they were immersed in arcane studies, their mind expanding to grasp the intricate threads that wove through the fabric of reality. However, their insatiable thirst for knowledge led them down a dangerous path. In their search for forbidden lore and forgotten spells, they delved into forbidden grimoires and flirted with the ancient forces that lurked in the shadows. Their reckless pursuit of power unleashed a calamitous event, resulting in the destruction of their family's estate. Consumed by guilt and determined to make amends, they embarked on a lifelong quest to master their chaotic magic and protect the world from the dangerous forces they once tempted.", "An outcast in a society that scorned their unique abilities, #{name} spent their formative years seeking refuge in dusty libraries and crumbling ruins. With no formal training, they taught themselves the intricacies of arcane magic, discovering an innate talent for bending the elements to their will. Their solitude allowed them to experiment freely, pushing the boundaries of what was thought possible. They became a master of elemental magic, wielding the destructive forces of fire, ice, lightning, and earth. Now, armed with their self-taught mastery, they wander the world as a scholar-adventurer, eager to uncover ancient relics and unravel the secrets of forgotten civilizations.", "Hailing from a lineage of renowned enchanters, #{name} was born with a rare gift - the ability to manipulate the very fabric of reality through illusions. From a young age, they fascinated their peers and elders with their mesmerizing displays of magic. Their illusions were so vivid, so intricate, that they blurred the line between fantasy and reality. They grew up as the court magician for a powerful ruler, their illusions serving as a tool to shape public opinion and conceal the monarch's secrets. However, they grew disillusioned with their role as a pawn in political games. They left their comfortable life behind, seeking to uncover the true nature of illusions and their own place in a world that often blurs the line between truth and deception."
      ]
    }

    character_class_name = self.character_class_type
    pre_generated_histories = histories_by_class[character_class_name]

    self.history = pre_generated_histories[rand(pre_generated_histories.size)] if pre_generated_histories
  end
end
